# Generated by Django 3.1 on 2020-09-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre de la Ciudad:')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido:')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cedula=')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección:')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Provincia')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
